# Generated by Django 3.2.14 on 2023-09-20 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_projectimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(default='bilding/media/images/IMG_4701.jpg', upload_to='images/'),
        ),
    ]
