# Generated by Django 3.2.14 on 2023-09-21 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_projectimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='budget',
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.DeleteModel(
            name='ProjectImage',
        ),
    ]
