# Generated by Django 4.2.5 on 2023-09-13 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_projectimage_requestimage_delete_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
