# Generated by Django 4.2.5 on 2023-09-13 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_request_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='url',
        ),
    ]
