# Generated by Django 4.2.5 on 2023-09-13 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_request_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='url',
            field=models.URLField(max_length=500, null=True),
        ),
    ]
