# Generated by Django 3.2.14 on 2023-09-22 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_projecturl_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecturl',
            name='url',
            field=models.URLField(),
        ),
    ]
