# Generated by Django 3.2.14 on 2023-09-22 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_projecturl_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projecturl',
            name='project',
        ),
    ]
