# Generated by Django 3.2.14 on 2023-09-22 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_projecturl_project'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectUrl',
        ),
        migrations.AddField(
            model_name='project',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
