# Generated by Django 3.2.14 on 2023-09-22 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20230922_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='url',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
