# Generated by Django 3.2.14 on 2023-09-22 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20230922_2212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='image1',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='request',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='request',
            name='image3',
        ),
    ]
