# Generated by Django 3.2.14 on 2023-09-22 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20230922_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='image1',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='request',
            name='image2',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='request',
            name='image3',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
