# Generated by Django 3.2.14 on 2023-09-22 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20230922_2243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestimage',
            name='image',
        ),
        migrations.AddField(
            model_name='requestimage',
            name='images',
            field=models.FileField(null=True, upload_to='images/'),
        ),
    ]
