# Generated by Django 3.2.14 on 2023-09-22 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20230922_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestimage',
            name='images',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
