# Generated by Django 3.2.14 on 2023-09-22 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_requestimage_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestimage',
            old_name='images',
            new_name='image',
        ),
    ]
