# Generated by Django 3.2.14 on 2023-09-23 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_rename_images_requestimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestimage',
            name='supplierapplication',
        ),
    ]
