# Generated by Django 3.2.14 on 2023-09-23 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_remove_requestimage_supplierapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.DeleteModel(
            name='RequestImage',
        ),
    ]
