# Generated by Django 3.2.14 on 2023-09-27 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20230923_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='request',
        ),
        migrations.AddField(
            model_name='request',
            name='items',
            field=models.ManyToManyField(to='core.Item'),
        ),
    ]
