# Generated by Django 3.2.14 on 2023-09-27 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20230927_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.request',null=True),
        ),
    ]
