# Generated by Django 3.2.14 on 2023-09-27 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_item_request'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='image1',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='project',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='project',
            name='image3',
        ),
        migrations.AlterField(
            model_name='item',
            name='amount',
            field=models.IntegerField(default=1),
        ),
    ]
