# Generated by Django 3.2.14 on 2023-09-27 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20230927_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='category',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='request',
            name='location',
            field=models.CharField(max_length=500),
        ),
    ]
