# Generated by Django 3.2.14 on 2023-09-27 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20230927_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestimage',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.request'),
        ),
    ]
