# Generated by Django 3.2.14 on 2023-09-29 05:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0031_auto_20230928_1341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='image',
            new_name='logo',
        ),
        migrations.AlterField(
            model_name='bidforproject',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applic', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='store',
            name='address',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='store',
            name='category',
            field=models.CharField(max_length=500),
        ),
    ]
