# Generated by Django 3.2.14 on 2023-09-30 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_alter_project_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='categories',
            field=models.CharField(blank=True, choices=[('Electrical', 'Electrical'), ('Plumbing', 'Plumbing'), ('Construction', 'Construction'), ('Plastering', 'Plastering'), ('Painting', 'Painting'), ('InteriorDecoration', 'InteriorDecoration')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='duration',
            field=models.CharField(blank=True, choices=[('1-6months', '1-6months'), ('1-2yrs', '1-2yrs'), ('1-5yrs', '1-5yrs')], default=0, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='experience',
            field=models.CharField(blank=True, choices=[('1-3yrs', '1-3yrs'), ('4-8yrs', '4-8yrs'), ('10-15yrs', '10-15yrs')], default=0, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='scope',
            field=models.CharField(blank=True, choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='RecentProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.project')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='recent_projects',
            field=models.ManyToManyField(related_name='projects', to='core.RecentProject'),
        ),
    ]
