# Generated by Django 3.2.14 on 2023-09-30 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20230930_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='category',
            field=models.CharField(choices=[('Electrical', 'Electrical'), ('Plumbing', 'Plumbing'), ('Construction', 'Construction'), ('Plastering', 'Plastering'), ('Painting', 'Painting'), ('InteriorDecoration', 'InteriorDecoration')], max_length=500),
        ),
    ]
