# Generated by Django 3.2.14 on 2023-09-30 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_alter_request_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='recent_projects',
        ),
    ]
