# Generated by Django 3.2.14 on 2023-09-30 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_remove_project_recent_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentproject',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='core.project'),
        ),
    ]
