# Generated by Django 3.2.14 on 2023-09-30 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_auto_20230930_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='recentproject',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
