# Generated by Django 3.2.14 on 2023-09-30 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_alter_recentproject_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recentproject',
            options={'ordering': ['-date']},
        ),
    ]
