# Generated by Django 3.2.14 on 2023-09-30 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_alter_recentproject_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='skills',
            field=models.CharField(blank=True, choices=[('Engineer', 'Engineer'), ('Electrician', 'Electrician'), ('Contractor', 'Contractor')], max_length=500, null=True),
        ),
    ]
