# Generated by Django 3.2.14 on 2023-10-03 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_alter_project_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
