# Generated by Django 3.2.14 on 2023-10-04 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_auto_20231003_2315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='image3',
        ),
    ]
