# Generated by Django 3.2.14 on 2023-10-04 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_remove_request_image3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='request',
            name='image2',
        ),
    ]
