# Generated by Django 3.2.14 on 2023-10-04 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_auto_20231004_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='request',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='request',
            name='image3',
        ),
    ]
