# Generated by Django 3.2.14 on 2023-10-08 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_alter_project_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date_time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
