# Generated by Django 3.2.14 on 2023-10-08 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_alter_project_date_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='date_time',
            new_name='time',
        ),
    ]
