# Generated by Django 3.2.14 on 2023-10-08 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_auto_20231008_1247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectimage',
            old_name='request',
            new_name='project',
        ),
    ]
