# Generated by Django 3.2.14 on 2023-10-09 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_alter_projectimage_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectimage',
            name='project',
        ),
        migrations.RemoveField(
            model_name='requestimage',
            name='request',
        ),
        migrations.AddField(
            model_name='project',
            name='applied',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='ProjectImage',
        ),
        migrations.DeleteModel(
            name='RequestImage',
        ),
    ]
