# Generated by Django 3.2.14 on 2023-10-10 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_auto_20231010_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidforproject',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bidforproject',
            name='duration',
            field=models.CharField(blank=True, choices=[('1-6months', '1-6months'), ('1-2yrs', '1-2yrs'), ('1-5yrs', '1-5yrs')], max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='image1',
            field=models.FileField(blank=True, null=True, upload_to='projectimages/'),
        ),
        migrations.AddField(
            model_name='project',
            name='image2',
            field=models.FileField(blank=True, null=True, upload_to='projectimages/'),
        ),
        migrations.AddField(
            model_name='project',
            name='image3',
            field=models.FileField(blank=True, null=True, upload_to='projectimages/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='applied',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.DeleteModel(
            name='ProjectImage',
        ),
    ]
