# Generated by Django 3.2.14 on 2023-10-10 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_auto_20231010_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='projectimages/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='projectimages/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='projectimages/'),
        ),
    ]
