# Generated by Django 3.2.14 on 2023-10-10 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_auto_20231010_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bidforproject',
            name='applicant',
        ),
    ]
