# Generated by Django 3.2.14 on 2023-10-10 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_bidforproject_applicant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidforproject',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.project'),
        ),
    ]
