# Generated by Django 3.2.14 on 2023-10-11 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_alter_bidforproject_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image3',
        ),
    ]
