# Generated by Django 3.2.14 on 2023-10-11 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_remove_project_image3'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RequestImage',
        ),
    ]
