# Generated by Django 3.2.14 on 2023-10-11 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_delete_requestimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='Requestimages/'),
        ),
        migrations.AddField(
            model_name='request',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='Requestimages/'),
        ),
    ]
