# Generated by Django 3.2.14 on 2023-10-11 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_auto_20231011_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
