# Generated by Django 3.2.14 on 2023-10-11 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_request_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bidforproject',
            name='date',
        ),
        migrations.AddField(
            model_name='bidforproject',
            name='time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
