# Generated by Django 3.2.14 on 2023-10-12 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_auto_20231011_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.request'),
        ),
    ]
