# Generated by Django 3.2.14 on 2023-10-12 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0072_alter_item_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.request'),
        ),
        migrations.CreateModel(
            name='UseHired',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(auto_now_add=True)),
                ('hirer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hirer', to=settings.AUTH_USER_MODEL)),
                ('hireree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hireree', to=settings.AUTH_USER_MODEL)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.project')),
            ],
        ),
    ]
