# Generated by Django 3.2.14 on 2023-10-12 14:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0073_auto_20231012_1419'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UseHired',
            new_name='UserHired',
        ),
    ]
