# Generated by Django 3.2.14 on 2023-10-12 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0074_rename_usehired_userhired'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(auto_now_add=True)),
                ('numnbers_of_hire_by_hiree', models.PositiveBigIntegerField(default=0)),
                ('hirer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hirer', to=settings.AUTH_USER_MODEL)),
                ('hireree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hireree', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='applied',
        ),
        migrations.AddField(
            model_name='project',
            name='assigned',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='UserHired',
        ),
        migrations.AddField(
            model_name='hire',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.project'),
        ),
    ]
