# Generated by Django 3.2.14 on 2023-10-12 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_alter_hire_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hire',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.project'),
        ),
    ]
