# Generated by Django 3.2.14 on 2023-10-16 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_alter_hire_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hire',
            name='numnbers_of_hire_by_hiree',
        ),
    ]
