# Generated by Django 3.2.14 on 2023-10-18 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0082_remove_hire_numnbers_of_hire_by_hiree'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-time']},
        ),
    ]
