# Generated by Django 3.2.14 on 2023-10-23 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0085_auto_20231022_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
