# Generated by Django 3.2.14 on 2023-10-24 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0086_notification_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='project',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='request',
        ),
        migrations.AddField(
            model_name='notification',
            name='read',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='time_stamp',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
