# Generated by Django 3.2.14 on 2023-10-24 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0087_auto_20231024_0919'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='title',
            new_name='message',
        ),
    ]
