# Generated by Django 3.2.14 on 2023-10-24 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0088_rename_title_notification_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliersapplication',
            name='bid_for_items',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.item'),
        ),
        migrations.AddField(
            model_name='suppliersapplication',
            name='delivery_inclusive',
            field=models.BooleanField(default=False),
        ),
    ]
