# Generated by Django 3.2.14 on 2023-10-24 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0090_auto_20231024_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='supplier_bid',
        ),
        migrations.CreateModel(
            name='BidItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('amount', models.IntegerField(default=1)),
                ('supplier_bid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.suppliersapplication')),
            ],
        ),
    ]
