# Generated by Django 3.2.14 on 2023-10-24 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0091_auto_20231024_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biditem',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
