# Generated by Django 3.2.14 on 2023-10-24 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0092_alter_biditem_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliersapplication',
            name='time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
