# Generated by Django 3.2.14 on 2023-10-24 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0095_auto_20231024_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppliersapplication',
            name='myrequest',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='myrequest', to='core.request'),
        ),
    ]
