# Generated by Django 3.2.14 on 2023-10-25 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0096_alter_suppliersapplication_myrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='assigned',
        ),
        migrations.AddField(
            model_name='bidforproject',
            name='assigned',
            field=models.BooleanField(default=False),
        ),
    ]
