# Generated by Django 3.2.14 on 2023-10-26 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0099_remove_biditem_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppliersapplication',
            name='myrequest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myrequest', to='core.request'),
        ),
    ]
