# Generated by Django 3.2.14 on 2023-10-27 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0101_auto_20231026_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliersapplication',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
