# Generated by Django 3.2.14 on 2023-10-27 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0102_suppliersapplication_accepted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='reviewer',
        ),
        migrations.AddField(
            model_name='reviews',
            name='reviewed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewed', to=settings.AUTH_USER_MODEL),
        ),
    ]
