# Generated by Django 3.2.14 on 2023-10-28 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0103_auto_20231027_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppliersapplication',
            name='letter',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='suppliersapplication',
            name='myrequest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='myrequest', to='core.request'),
        ),
        migrations.AlterField(
            model_name='suppliersapplication',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.store'),
        ),
    ]
