# Generated by Django 3.2.14 on 2023-10-29 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0045_store'),
        ('core', '0104_auto_20231028_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidforproject',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='core.project'),
        ),
        migrations.AlterField(
            model_name='suppliersapplication',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.store'),
        ),
        migrations.DeleteModel(
            name='Store',
        ),
    ]
