# Generated by Django 4.2.5 on 2023-09-14 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(default='CO', max_length=250),
            preserve_default=False,
        ),
    ]
