# Generated by Django 3.2.14 on 2023-09-17 11:56

from django.db import migrations,models



class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_remove_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.PositiveBigIntegerField(null=True)
        ),
    ]
