# Generated by Django 3.2.14 on 2023-09-18 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_alter_user_bvnimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bvnimage',
        ),
        migrations.AddField(
            model_name='user',
            name='gov_id_image',
            field=models.FileField(null=True, upload_to='files/'),
        ),
    ]
