# Generated by Django 3.2.14 on 2023-09-20 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_auto_20230918_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='updates',
            field=models.BooleanField(default=False),
        ),
    ]
