# Generated by Django 3.2.14 on 2023-09-21 12:02

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_user_updates'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='authMedium',
            field=models.CharField(default='email', max_length=50),
        ),
        
    ]
