# Generated by Django 3.2.14 on 2023-09-21 12:29

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_auto_20230921_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='location',
            field=django_countries.fields.CharField(max_length=250, null=True),
        ),
    ]
