# Generated by Django 3.2.14 on 2023-10-05 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_auto_20231005_1926'),
    ]

    # operations = [
    #     migrations.AddField(
    #         model_name='user',
    #         name='hires',
    #         field=models.PositiveIntegerField(default=0),
    #     ),
    # ]
