# Generated by Django 3.2.14 on 2023-10-05 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_auto_20231005_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='updateuser',
            name='hires',
        ),
        migrations.RemoveField(
            model_name='updateuser',
            name='image',
        ),
        migrations.AddField(
            model_name='updateuser',
            name='address',
            field=models.TextField(default='shofunwa'),
        ),
    ]
