# Generated by Django 3.2.14 on 2023-10-05 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_auto_20231005_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='updateuser',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='authentication.updateuser'),
        ),
    ]
