# Generated by Django 3.2.14 on 2023-10-05 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_user_hires'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
    ]
