# Generated by Django 3.2.14 on 2023-10-05 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0018_remove_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='firstname',
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        # migrations.AddField(
        #     model_name='user',
        #     name='address',
        #     field=models.CharField(blank=True, null=True),
        # ),
        # migrations.AddField(
        #     model_name='user',
        #     name='bvn',
        #     field=models.PositiveBigIntegerField(blank=True, null=True),
        # ),
        # migrations.AddField(
        #     model_name='user',
        #     name='gov_id_image',
        #     field=models.ImageField(blank=True, null=True, upload_to=''),
        # ),
    ]
