# Generated by Django 3.2.14 on 2023-10-05 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0019_auto_20231005_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.TextField(default='shofunwa'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bvn',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gov_id_image',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
