# Generated by Django 3.2.14 on 2023-10-06 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0021_auto_20231005_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hires',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
