# Generated by Django 3.2.14 on 2023-10-06 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0022_alter_user_hires'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bvn',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gov_id_image',
        ),
        migrations.RemoveField(
            model_name='user',
            name='hires',
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bvn', models.PositiveBigIntegerField(null=True)),
                ('gov_id_image', models.FileField(blank=True, null=True, upload_to='files/')),
                ('hires', models.PositiveIntegerField(default=0)),
                ('address', models.TextField(default='shofunwa')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
