# Generated by Django 3.2.14 on 2023-10-06 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0024_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pics',
            field=models.ImageField(blank=True, null=True, upload_to='files/'),
        ),
    ]
