# Generated by Django 3.2.14 on 2023-10-06 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0025_user_profile_pics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
    ]
