# Generated by Django 3.2.14 on 2023-10-10 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0027_favourites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='hires',
        ),
    ]
