# Generated by Django 3.2.14 on 2023-10-10 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0028_remove_profile_hires'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hires',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
