# Generated by Django 3.2.14 on 2023-10-12 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0032_auto_20231012_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hired',
            field=models.BooleanField(default=False),
        ),
    ]
