# Generated by Django 3.2.14 on 2023-10-16 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0033_profile_hired'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='hired',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='hires',
        ),
        migrations.AddField(
            model_name='user',
            name='hired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='hires',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
