# Generated by Django 3.2.14 on 2023-10-16 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0034_auto_20231016_1022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='hired',
        ),
    ]
