# Generated by Django 3.2.14 on 2023-10-20 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0035_remove_user_hired'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='state',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
