# Generated by Django 3.2.14 on 2023-10-22 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0038_changepassword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='changepassword',
            name='email',
        ),
        migrations.RemoveField(
            model_name='changepassword',
            name='password',
        ),
        migrations.AddField(
            model_name='changepassword',
            name='newpassword',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='changepassword',
            name='oldpassword',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
