# Generated by Django 3.2.14 on 2023-10-25 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0042_alter_user_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bvn',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
