# Generated by Django 3.2.14 on 2023-10-29 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0106_auto_20231029_0655'),
        ('authentication', '0045_store'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Store',
        ),
    ]
